# Generated by Django 2.2.4 on 2023-04-27 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipalite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_valeur', models.CharField(max_length=20)),
                ('reponse_en', models.CharField(max_length=200)),
                ('reponse_fr', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['reponse_en'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_en', models.CharField(max_length=30)),
                ('reponse_fr', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_valeur', models.CharField(max_length=200)),
                ('reponse_en', models.CharField(max_length=200)),
                ('reponse_fr', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_valeur', models.CharField(max_length=200)),
                ('reponse_en', models.CharField(max_length=200)),
                ('reponse_fr', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_valeur', models.CharField(max_length=200)),
                ('reponse_en', models.CharField(max_length=200)),
                ('reponse_fr', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personnegrcntp1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeGRC', models.CharField(max_length=30, verbose_name='ID')),
                ('delit', models.IntegerField(default=1, verbose_name='Présence ancien délits')),
                ('alias', models.IntegerField(default=1, verbose_name='Présence ancien alias')),
                ('dateprint1', models.DateField(verbose_name='Ancienne date print')),
                ('oldpresencefps', models.IntegerField(verbose_name='Présence ancien FPS')),
                ('dateprint2', models.DateField(blank=True, null=True, verbose_name='Date print. Laisser vide si pas de fichier (jj/mm/aaaa)')),
                ('newdelit', models.BooleanField(default=1, verbose_name='Présence de délits après la date du dernier verdict rentré')),
                ('newpresencefps', models.BooleanField(verbose_name='Présence de FPS en 2019/20. Cocher si oui')),
                ('dateverdictder', models.DateField(blank=True, null=True, verbose_name='Date du dernier verdict présent dans la fiche. Laisser vide si pas de fichier (jj/mm/aaaa)')),
                ('ferme', models.BooleanField()),
                ('datedeces', models.DateField(blank=True, null=True, verbose_name='Si décédé indiquer la date ici (jj/mm/aaaa)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('RA', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NTP1Reprise.Province')),
            ],
            options={
                'ordering': ['codeGRC'],
            },
        ),
        migrations.CreateModel(
            name='NouveauxDelitsntp1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sentence', models.DateField(verbose_name='Date de la décision (jj/mm/aaaa)')),
                ('ordre_delit', models.IntegerField(default=1, verbose_name='Ordre')),
                ('codeCCdelit', models.CharField(max_length=30, verbose_name='Code CC du delit (si pas CC preciser de quel code il s agit)')),
                ('nombre_chefs', models.IntegerField(default=1, verbose_name='Nombre de chefs')),
                ('amendeON', models.BooleanField(verbose_name='Amende? Cocher si oui')),
                ('detentionON', models.BooleanField(verbose_name='Détention? Cocher si oui')),
                ('probationON', models.BooleanField(verbose_name='Probation? Cocher si oui')),
                ('interdictionON', models.BooleanField(verbose_name='Interdiction? Cocher si oui')),
                ('surcisON', models.BooleanField(verbose_name='Surcis? Cocher si oui')),
                ('autreON', models.BooleanField(verbose_name='Autre? Cocher si oui')),
                ('autredetails', models.CharField(blank=True, max_length=100, null=True, verbose_name='Si autre : détails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.IntegerField(default=1)),
                ('nouveaudelit', models.BooleanField()),
                ('RA', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('lieu_sentence', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NTP1Reprise.Municipalite', verbose_name='Lieu du verdict')),
                ('personnegrc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NTP1Reprise.Personnegrcntp1', verbose_name='ID')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NTP1Reprise.Province')),
                ('type_tribunal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NTP1Reprise.Tribunal', verbose_name='Type de tribunal')),
                ('verdict', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='verdict', to='NTP1Reprise.Verdict', verbose_name='Verdict')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NTP1Reprise.Violation', verbose_name='Code de violation')),
            ],
            options={
                'ordering': ['personnegrc', 'date_sentence', 'ordre_delit'],
            },
        ),
        migrations.AddField(
            model_name='municipalite',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NTP1Reprise.Province'),
        ),
        migrations.CreateModel(
            name='Liberationntp1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_liberation', models.DateField(verbose_name='Date de la libération (jj/mm/aaaa)')),
                ('type', models.BooleanField(verbose_name='Libération absolue? Cocher si oui')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('RA', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('personnegrc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NTP1Reprise.Personnegrcntp1', verbose_name='ID')),
            ],
            options={
                'ordering': ['personnegrc', 'date_liberation'],
            },
        ),
        migrations.AddIndex(
            model_name='nouveauxdelitsntp1',
            index=models.Index(fields=['personnegrc', 'date_sentence', 'ordre_delit', 'RA'], name='NTP1Reprise_personn_d68b27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nouveauxdelitsntp1',
            unique_together={('personnegrc', 'date_sentence', 'ordre_delit', 'RA')},
        ),
    ]
