# Generated by Django 2.2.4 on 2023-05-26 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTP1Reprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_valeur', models.CharField(max_length=20)),
                ('reponse_en', models.CharField(max_length=200)),
                ('reponse_fr', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['reponse_fr'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_valeur', models.CharField(max_length=20)),
                ('reponse_en', models.CharField(max_length=200)),
                ('reponse_fr', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['reponse_fr'],
            },
        ),
        migrations.AlterModelOptions(
            name='municipalite',
            options={'ordering': ['reponse_fr']},
        ),
        migrations.RemoveField(
            model_name='nouveauxdelitsntp1',
            name='province',
        ),
        migrations.AddField(
            model_name='nouveauxdelitsntp1',
            name='amendecout',
            field=models.IntegerField(blank=True, null=True, verbose_name="Cout total de l'amende"),
        ),
        migrations.AddField(
            model_name='nouveauxdelitsntp1',
            name='consecutifsON',
            field=models.BooleanField(default=0, verbose_name='Consécutif? Cocher si oui'),
        ),
        migrations.AddField(
            model_name='nouveauxdelitsntp1',
            name='descriptiondelit',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Description du délit'),
        ),
        migrations.AddField(
            model_name='nouveauxdelitsntp1',
            name='detentionduree',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée de la détention'),
        ),
        migrations.AddField(
            model_name='nouveauxdelitsntp1',
            name='interdictiondetails',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Détails à propos de l'interdicttion"),
        ),
        migrations.AddField(
            model_name='nouveauxdelitsntp1',
            name='interdictionduree',
            field=models.IntegerField(blank=True, null=True, verbose_name="Durée de l'interdiction"),
        ),
        migrations.AddField(
            model_name='nouveauxdelitsntp1',
            name='probationduree',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée de la probation'),
        ),
        migrations.AddField(
            model_name='nouveauxdelitsntp1',
            name='surcisduree',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée du surcis'),
        ),
        migrations.AlterField(
            model_name='nouveauxdelitsntp1',
            name='codeCCdelit',
            field=models.CharField(max_length=50, verbose_name='Code CC du delit (si pas CC preciser de quel code il s agit)'),
        ),
        migrations.AddField(
            model_name='nouveauxdelitsntp1',
            name='amende_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTP1Reprise.Type', verbose_name="Caractéristiques de l'amende"),
        ),
        migrations.AddField(
            model_name='nouveauxdelitsntp1',
            name='unitedetention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='duree_detention', to='NTP1Reprise.Duree', verbose_name='Jours, mois, ans etc?'),
        ),
        migrations.AddField(
            model_name='nouveauxdelitsntp1',
            name='uniteinterdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='duree_interdiction', to='NTP1Reprise.Duree', verbose_name='Jours, mois, ans etc?'),
        ),
        migrations.AddField(
            model_name='nouveauxdelitsntp1',
            name='uniteprobation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='duree_probation', to='NTP1Reprise.Duree', verbose_name='Jours, mois, ans etc?'),
        ),
        migrations.AddField(
            model_name='nouveauxdelitsntp1',
            name='unitesurcis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='duree_surcis', to='NTP1Reprise.Duree', verbose_name='Jours, mois, ans etc?'),
        ),
    ]
