# Generated by Django 2.2.4 on 2023-05-26 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTP1Reprise', '0002_auto_20230526_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnegrcntp1',
            name='RA',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personnegrcntp1',
            name='newpresencefps',
            field=models.BooleanField(verbose_name='Présence de FPS en 2022/23. Cocher si oui'),
        ),
    ]
