# Generated by Django 2.2.4 on 2023-05-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTP1Reprise', '0003_auto_20230526_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nouveauxdelitsntp1',
            name='amendecout',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Cout total de l'amende"),
        ),
    ]
