# Generated by Django 2.2.4 on 2023-05-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTP1Reprise', '0006_auto_20230531_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nouveauxdelitsntp1',
            name='detentionduree',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Durée de la détention'),
        ),
    ]
