# Generated by Django 2.2.4 on 2023-06-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTP1Reprise', '0007_auto_20230531_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnegrcntp1',
            name='codeGRC',
            field=models.IntegerField(verbose_name='ID'),
        ),
    ]
