# Generated by Django 2.2.4 on 2023-10-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTP1Reprise', '0009_auto_20230608_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duree',
            options={'ordering': ['reponse_valeur']},
        ),
        migrations.RemoveField(
            model_name='nouveauxdelitsntp1',
            name='consecutifsON',
        ),
        migrations.AlterField(
            model_name='nouveauxdelitsntp1',
            name='amendeON',
            field=models.BooleanField(verbose_name='Amende, frais etc.? Cocher si oui'),
        ),
        migrations.AlterField(
            model_name='nouveauxdelitsntp1',
            name='amendecout',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Cout total de l'amende (+ surmende + frais + restitution)"),
        ),
        migrations.AlterField(
            model_name='nouveauxdelitsntp1',
            name='detentionduree',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Durée de la détention (ajouter sentence + présentence)'),
        ),
        migrations.AlterField(
            model_name='nouveauxdelitsntp1',
            name='interdictiondetails',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Détails à propos de l'interdiction"),
        ),
    ]
