# Generated by Django 2.2.4 on 2023-10-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTP1Reprise', '0010_auto_20231003_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnegrcntp1',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='personnegrcntp1',
            name='dateprint1',
        ),
        migrations.RemoveField(
            model_name='personnegrcntp1',
            name='dateverdictder',
        ),
        migrations.RemoveField(
            model_name='personnegrcntp1',
            name='delit',
        ),
        migrations.RemoveField(
            model_name='personnegrcntp1',
            name='newdelit',
        ),
        migrations.RemoveField(
            model_name='personnegrcntp1',
            name='oldpresencefps',
        ),
        migrations.AlterField(
            model_name='personnegrcntp1',
            name='newpresencefps',
            field=models.BooleanField(verbose_name='Présence de FPS. Cocher si oui'),
        ),
    ]
