# Generated by Django 2.2.4 on 2023-10-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTP1Reprise', '0012_personnegrcntp1_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnegrcntp1',
            name='codeGRC',
            field=models.CharField(max_length=50, verbose_name='ID'),
        ),
    ]
