# Generated by Django 2.2.4 on 2023-10-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTP1Reprise', '0013_auto_20231016_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnegrcntp1',
            name='ferme',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='personnegrcntp1',
            name='newpresencefps',
            field=models.BooleanField(default=0, verbose_name='Présence de FPS. Cocher si oui'),
        ),
    ]
