# Generated by Django 2.2.4 on 2023-10-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTP1Reprise', '0014_auto_20231016_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnegrcntp1',
            name='ferme',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personnegrcntp1',
            name='newpresencefps',
            field=models.BooleanField(blank=True, null=True, verbose_name='Présence de FPS. Cocher si oui'),
        ),
    ]
